name: NPM publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node and pnpm
        uses: uxiew/action-setup-node-pnpm@v1
        with:
          node-version: 20.x
          pnpm-version: 9.12.0
          registry-url: https://registry.npmjs.org/

      - name: install, build, and test
        run: |
          pnpm install
          pnpm build
          pnpm test

      - name: Publish to jsr.io
        run: pnpm dlx jsr publish --allow-dirty

      - name: Publish to NPM
        continue-on-error: true
        env:
          # setting the "npm_config_//registry.npmjs.org/:_authToken" env variable directly doesn't work.
          # probably "pnpm release" doesn't pass auth tokens to child processes
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # pnpm config set is broken
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm publish --no-git-checks
